config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :drink_ingredients, only: [:index, :show], defaults: { format: :json }
  resources :ingredients, only: [:index, :show], defaults: { format: :json }
=======
 
  resources :drinks,only: [:index, :show, :edit, :update]
  resources :ingredients,only: [:index, :show]
  resources :glasses, only: [:index, :show]
  resources :drink_ingredients, only: [:show]
>>>>>>> origin/master
  root 'homepage#index'
  get '/api/drinks/:id', to: 'drinks#show'
  get '/api/drinks', to: 'drinks#index'
  match '*path' => 'homepage#index', via: :all
<<<<<<< HEAD
  namespace :api do
    resources :drinks, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
=======
>>>>>>> origin/master
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :glass
end

app/models/drink_ingredient.rb
class DrinkIngredient < ApplicationRecord
  belongs_to :drink
end

app/models/droptable.rb
class Droptable < ApplicationRecord
end

app/models/glass.rb
class Glass < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drink_ingredients_controller.rb
class DrinkIngredientsController < ApplicationController
<<<<<<< HEAD
  def index
    @drink_ingredients = DrinkIngredient.all
    render json: @drink_ingredients
  end

  def show
    @drink_ingredient = DrinkIngredient.find(params[:id])
    render json: @drink_ingredient
=======
  def show
    @drink_ingredients = DrinkIngredient.all
    if params[:id]
      @drink_id_list = @drink_ingredients.where("ingredient_id=?","#{params[:id]}").pluck(:drink_id)

      @drink_ingredient = @drink_id_list.map {|id|{id:id,ingredients_id_list:@drink_ingredients.where("drink_id=?",id).pluck(:ingredient_id)}         
      } 
      
      @ingredientlist = DrinkIngredient.where(drink_id: @drink_id_list).where("ingredient_id!=?","#{params[:id]}").distinct.pluck(:ingredient_id)
    end
    render json: @result = {drink_ingredient:@drink_ingredient,available_ingredient_list:@ingredientlist}
>>>>>>> origin/master
  end
end

app/controllers/drink_mixer_controller.rb
class DrinkMixerController < ApplicationController
  def index
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @drinks = Drink.pluck(:id, :name,:image,:tags).map{|i,n,img,t|{id:i,name:n,image:img,tags:t}} 
   # #render json: @drinks
    respond_to do |format|
        format.html # Render the HTML template
        format.json { render 'index.json.jbuilder' } # Render the JSON template
    end
  end

  def show
   @drink = Drink.find(params[:id])
  #  render json: @drink
   respond_to do |format|
    format.html # Render the HTML template
    format.json { render 'show.json.jbuilder' } # Render the JSON template
  end
  
end

end


# class DrinksController < ApplicationController

#   def index
#         @drinks = Drink.all
#         render :json => @drinks
#   end

#   def show
#     @drink = Drink.find(params[:id])
#     render json: @drink
#   end

# end

app/controllers/glasses_controller.rb
class GlassesController < ApplicationController
  def index
    @glasses = Glass.all
    respond_to do |format|
      format.html # Render the HTML template
      format.json { render json: @glasses } # Render the JSON template
  end
  end

  def show
    @glasses = Glass.all
    if params[:id]
      @drink_list_byglass = Drink.where("glass_id=?","#{params[:id]}").pluck(:id)
      
      @drink_ingredient_byglass = @drink_list_byglass.map {|id|{id:id,ingredients_id_list:DrinkIngredient.where("drink_id=?",id).pluck(:ingredient_id)}         
      } 
      
      @ingredient_list_byglass = DrinkIngredient.where(drink_id: @drink_list_byglass).distinct.pluck(:ingredient_id)
    end
    render json: @result = {drink_ingredient:@drink_ingredient_byglass,available_ingredient_list:@ingredient_list_byglass}
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
<<<<<<< HEAD

  def index
		@ingredients = Ingredient.all
		render :json => @ingredients
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    render json: @ingredient
  end
  
=======
  def index
    @ingredients = Ingredient.pluck(:name,:image_s,:id).map{|name,image,id|{name:name,image:"https://" + URI::DEFAULT_PARSER.escape(image),id:id}} 
    respond_to do |format|
      format.html # Render the HTML template
      format.json { render 'index.json.jbuilder' } # Render the JSON template
  end
  end
>>>>>>> origin/master
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drink_ingredients_helper.rb
module DrinkIngredientsHelper
end

app/helpers/drink_mixer_helper.rb
module DrinkMixerHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/glasses_helper.rb
module GlassesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/drink_ingredients/show.html.erb
<h1>DrinkIngredients#show</h1>
<p>Find me in app/views/drink_ingredients/show.html.erb</p>

app/views/drinks/_drink.html.erb
      
      <div>
      <img src = "<%=drink[:image]%>" title= "<%= drink[:name]%>" width = "300" >
      <i><%=drink[:name]%> </i>
      <i>"<%=drink[:tags]%>"</i>
      <p><%=drink[:instruction]%>
      </div>

app/views/drinks/index.html.erb
<h1>Drinks#index</h1>
<h2><%= link_to "Go to ingredients", ingredients_path %></h2>
<div class = drink_list>

<% @drinks.each do |d|%>
      <img src = "<%=d[:image]%>" title= "<%= d[:name]%>" width = "250" >
      <i><%=d[:name]%> </i>
      <i>"<%=d[:tags]%>"</i>
      <%end%>
  </div>
<button> <H1>Load more ....</H1></button>

app/views/drinks/show.html.erb
<h1>Drinks#show</h1>
<h2><%= link_to "Go to ingredients", ingredients_path %></h2>
<%= render @drink %>

app/views/glasses/index.html.erb
<h1>Glasses#index</h1>

<div class = glass_list>
      <% @glasses.each do |g|%>
      <img src="<%=g[:image]%>" title= "<%= g[:name]%>" >
       <i><%=g[:name]%></i>
   <%end %>
  </div>

app/views/glasses/show.html.erb
<h1>Glasses#show</h1>
<p>Find me in app/views/glasses/show.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<h2><%= link_to "Go to drinks", drinks_path%></h2>
<div class = ingredient_list>
<% @ingredients.each do |i|%>
    <img src = <%= i[:image]%> title= "<%= i[:name]%>" >
    <i><%=i[:name]%></i>
    <%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CocktailSpirit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'Index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/drinks/index.html.erb
<h1>Drinks</h1>

<ul>
  <% @drinks.each do |drink| %>
    <li>
      <h2><%= drink.name %></h2>
      <%= image_tag drink.image, class: "drink-image" %>
    </li>
  <% end %>
</ul>